package com.kien.lp.myapplication.string;

import java.util.ArrayList;
import java.util.List;

public class String_CounTry {
   public String Country = " 1 => 'Afghanistan',\n" +
            "        2 => 'Albania',\n" +
            "        3 => 'Algeria',\n" +
            "        4 => 'American Samoa',\n" +
            "        5 => 'Andorra',\n" +
            "        6 => 'Angola',\n" +
            "        7 => 'Anguilla',\n" +
            "        8 => 'Antarctica',\n" +
            "        9 => 'Antigua and Barbuda',\n" +
            "        10 => 'Argentina',\n" +
            "        11 => 'Armenia',\n" +
            "        12 => 'Aruba',\n" +
            "        13 => 'Australia',\n" +
            "        14 => 'Austria',\n" +
            "        15 => 'Azerbaijan',\n" +
            "        16 => 'Bahamas ',\n" +
            "        17 => 'Bahrain',\n" +
            "        18 => 'Bangladesh',\n" +
            "        19 => 'Barbados',\n" +
            "        20 => 'Belarus',\n" +
            "        21 => 'Belgium',\n" +
            "        22 => 'Belize',\n" +
            "        23 => 'Benin',\n" +
            "        24 => 'Bermuda',\n" +
            "        25 => 'Bhutan',\n" +
            "        26 => 'Bolivia',\n" +
            "        27 => 'Bosnia and Herzegovina',\n" +
            "        28 => 'Botswana',\n" +
            "        29 => 'Bouvet Island',\n" +
            "        30 => 'Brazil',\n" +
            "        31 => 'British Indian Ocean Territory',\n" +
            "        32 => 'Brunei',\n" +
            "        33 => 'Bulgaria',\n" +
            "        34 => 'Burkina Faso',\n" +
            "        35 => 'Burundi',\n" +
            "        36 => 'Cambodia',\n" +
            "        37 => 'Cameroon',\n" +
            "        38 => 'Canada',\n" +
            "        39 => 'Canary Islands',\n" +
            "        40 => 'Cape Verde',\n" +
            "        41 => 'Cayman Islands',\n" +
            "        42 => 'Central African Republic',\n" +
            "        43 => 'Chad',\n" +
            "        44 => 'Chile',\n" +
            "        45 => 'China',\n" +
            "        46 => 'Christmas Island',\n" +
            "        47 => 'Cocos (Keeling) Islands',\n" +
            "        48 => 'Colombia',\n" +
            "        49 => 'Comoros',\n" +
            "        50 => 'Congo',\n" +
            "        51 => 'Congo, Democractic Republic of the',\n" +
            "        52 => 'Cook Islands',\n" +
            "        53 => 'Costa Rica',\n" +
            "        54 => 'Cote d Ivoire',\n" +
            "        55 => 'Croatia (Hrvatska)',\n" +
            "        56 => 'Cuba',\n" +
            "        57 => 'Cyprus',\n" +
            "        58 => 'Czech Republic',\n" +
            "        59 => 'Denmark',\n" +
            "        60 => 'Djibouti',\n" +
            "        61 => 'Dominica',\n" +
            "        62 => 'Dominican Republic',\n" +
            "        63 => 'East Timor',\n" +
            "        64 => 'Ecuador',\n" +
            "        65 => 'Egypt',\n" +
            "        66 => 'El Salvador',\n" +
            "        67 => 'Equatorial Guinea',\n" +
            "        68 => 'Eritrea',\n" +
            "        69 => 'Estonia',\n" +
            "        70 => 'Ethiopia',\n" +
            "        71 => 'Falkland Islands (Islas Malvinas)',\n" +
            "        72 => 'Faroe Islands',\n" +
            "        73 => 'Fiji Islands',\n" +
            "        74 => 'Finland',\n" +
            "        75 => 'France',\n" +
            "        76 => 'French Guiana',\n" +
            "        77 => 'French Polynesia',\n" +
            "        78 => 'French Southern Territories',\n" +
            "        79 => 'Gabon',\n" +
            "        80 => 'Gambia, The',\n" +
            "        81 => 'Georgia',\n" +
            "        82 => 'Germany',\n" +
            "        83 => 'Ghana',\n" +
            "        84 => 'Gibraltar',\n" +
            "        85 => 'Greece',\n" +
            "        86 => 'Greenland',\n" +
            "        87 => 'Grenada',\n" +
            "        88 => 'Guadeloupe',\n" +
            "        89 => 'Guam',\n" +
            "        90 => 'Guatemala',\n" +
            "        91 => 'Guernsey',\n" +
            "        92 => 'Guinea',\n" +
            "        93 => 'Guinea-Bissau',\n" +
            "        94 => 'Guyana',\n" +
            "        95 => 'Haiti',\n" +
            "        96 => 'Heard and McDonald Islands',\n" +
            "        97 => 'Honduras',\n" +
            "        98 => 'Hong Kong',\n" +
            "        99 => 'Hungary',\n" +
            "        100 => 'Iceland',\n" +
            "        101 => 'India',\n" +
            "        102 => 'Indonesia',\n" +
            "        103 => 'Iran',\n" +
            "        104 => 'Iraq',\n" +
            "        105 => 'Ireland',\n" +
            "        106 => 'Isle of Man',\n" +
            "        107 => 'Israel',\n" +
            "        108 => 'Italy',\n" +
            "        109 => 'Ivory Coast',\n" +
            "        110 => 'Jamaica',\n" +
            "        111 => 'Japan',\n" +
            "        112 => 'Jersey',\n" +
            "        113 => 'Jordan',\n" +
            "        114 => 'Kazakhstan',\n" +
            "        115 => 'Kenya',\n" +
            "        116 => 'Kiribati',\n" +
            "        117 => 'Korea',\n" +
            "        118 => 'Korea, North',\n" +
            "        119 => 'Kosovo',\n" +
            "        120 => 'Kuwait',\n" +
            "        121 => 'Kyrgyzstan',\n" +
            "        122 => 'Laos',\n" +
            "        123 => 'Latvia',\n" +
            "        124 => 'Lebanon',\n" +
            "        125 => 'Lesotho',\n" +
            "        126 => 'Liberia',\n" +
            "        127 => 'Libya',\n" +
            "        128 => 'Liechtenstein',\n" +
            "        129 => 'Lithuania',\n" +
            "        130 => 'Luxembourg',\n" +
            "        131 => 'Macau S.A.R.',\n" +
            "        132 => 'Macedonia',\n" +
            "        133 => 'Madagascar',\n" +
            "        134 => 'Malawi',\n" +
            "        135 => 'Malaysia',\n" +
            "        136 => 'Maldives',\n" +
            "        137 => 'Mali',\n" +
            "        138 => 'Malta',\n" +
            "        139 => 'Marshall Islands',\n" +
            "        140 => 'Martinique',\n" +
            "        141 => 'Mauritania',\n" +
            "        142 => 'Mauritius',\n" +
            "        143 => 'Mayotte Island (Comoros)',\n" +
            "        144 => 'Mexico',\n" +
            "        145 => 'Micronesia',\n" +
            "        146 => 'Moldova',\n" +
            "        147 => 'Monaco',\n" +
            "        148 => 'Mongolia',\n" +
            "        149 => 'Montenegro',\n" +
            "        150 => 'Montserrat',\n" +
            "        151 => 'Morocco',\n" +
            "        152 => 'Mozambique',\n" +
            "        153 => 'Myanmar',\n" +
            "        154 => 'Namibia',\n" +
            "        155 => 'Nauru',\n" +
            "        156 => 'Nepal',\n" +
            "        157 => 'Netherlands',\n" +
            "        158 => 'Netherlands Antilles',\n" +
            "        159 => 'New Caledonia',\n" +
            "        160 => 'New Zealand',\n" +
            "        161 => 'Nicaragua',\n" +
            "        162 => 'Niger',\n" +
            "        163 => 'Nigeria',\n" +
            "        164 => 'Niue',\n" +
            "        165 => 'Norfolk Island',\n" +
            "        166 => 'Northern Mariana Islands',\n" +
            "        167 => 'Norway',\n" +
            "        168 => 'Oman',\n" +
            "        169 => 'Pakistan',\n" +
            "        170 => 'Palau',\n" +
            "        171 => 'Panama',\n" +
            "        172 => 'Papua new Guinea',\n" +
            "        173 => 'Paraguay',\n" +
            "        174 => 'Peru',\n" +
            "        175 => 'Philippines',\n" +
            "        176 => 'Pitcairn Island',\n" +
            "        177 => 'Poland',\n" +
            "        178 => 'Portugal',\n" +
            "        179 => 'Puerto Rico',\n" +
            "        180 => 'Qatar',\n" +
            "        181 => 'Reunion',\n" +
            "        182 => 'Romania',\n" +
            "        183 => 'Russia',\n" +
            "        184 => 'Rwanda',\n" +
            "        185 => 'Saint Helena',\n" +
            "        186 => 'Saint Kitts And Nevis',\n" +
            "        187 => 'Saint Lucia',\n" +
            "        188 => 'Saint Pierre and Miquelon',\n" +
            "        189 => 'Saint Vincent And The Grenadines',\n" +
            "        190 => 'Saipan',\n" +
            "        191 => 'Samoa (American)',\n" +
            "        192 => 'Samoa (Western)',\n" +
            "        193 => 'San Marino',\n" +
            "        194 => 'Sao Tome and Principe',\n" +
            "        195 => 'Saudi Arabia',\n" +
            "        196 => 'Scandinavia',\n" +
            "        197 => 'Senegal',\n" +
            "        198 => 'Serbia',\n" +
            "        199 => 'Seychelles',\n" +
            "        200 => 'Sierra Leone',\n" +
            "        201 => 'Singapore',\n" +
            "        202 => 'Slovakia',\n" +
            "        203 => 'Slovenia',\n" +
            "        204 => 'Solomon Islands',\n" +
            "        205 => 'Somalia',\n" +
            "        206 => 'South Africa',\n" +
            "        207 => 'South Georgia And The South Sandwich Islands',\n" +
            "        208 => 'Spain',\n" +
            "        209 => 'Sri Lanka',\n" +
            "        210 => 'Sudan',\n" +
            "        211 => 'Suriname',\n" +
            "        212 => 'Svalbard And Jan Mayen Islands',\n" +
            "        213 => 'Swaziland',\n" +
            "        214 => 'Sweden',\n" +
            "        215 => 'Switzerland',\n" +
            "        216 => 'Syria',\n" +
            "        217 => 'Taiwan',\n" +
            "        218 => 'Tajikistan',\n" +
            "        219 => 'Tanzania',\n" +
            "        220 => 'Thailand',\n" +
            "        221 => 'Togo',\n" +
            "        222 => 'Tokelau',\n" +
            "        223 => 'Tonga',\n" +
            "        224 => 'Trinidad And Tobago',\n" +
            "        225 => 'Tunisia',\n" +
            "        226 => 'Turkey',\n" +
            "        227 => 'Turkmenistan',\n" +
            "        228 => 'Turks And Caicos Islands',\n" +
            "        229 => 'Tuvalu',\n" +
            "        230 => 'U.K.',\n" +
            "        231 => 'USA',\n" +
            "        232 => 'Uganda',\n" +
            "        233 => 'Ukraine',\n" +
            "        234 => 'United Arab Emirates',\n" +
            "        235 => 'United States Minor Outlying Islands',\n" +
            "        236 => 'Uruguay',\n" +
            "        237 => 'Uzbekistan',\n" +
            "        238 => 'Vanuatu',\n" +
            "        239 => 'Vatican City State (Holy See)',\n" +
            "        240 => 'Venezuela',\n" +
            "        241 => 'Vietnam',\n" +
            "        242 => 'Virgin Islands (British)',\n" +
            "        243 => 'Virgin Islands (US)',\n" +
            "        244 => 'Wallis And Futuna Islands',\n" +
            "        245 => 'Yemen',\n" +
            "        246 => 'Yugoslavia',\n" +
            "        247 => 'Zambia',\n" +
            "        248 => 'Zanaibar',\n" +
            "        249 => 'Zimbabwe'";

 public  String[] separated = Country.split("'");
 public int size_list = separated.length;
 public List<String> mCountry = new ArrayList<>();


}
